name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: [windows-latest]
    steps:
      - name: hyper-v
        run: |
          Enable-WindowsOptionalFeature `
            -FeatureName "Microsoft-Hyper-V", "Containers" `
            -Online `
            -All `
            -NoRestart ;
      - name: LCOW
        run: |
          Invoke-WebRequest -Uri "https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip" -UseBasicParsing -OutFile release.zip
          Expand-Archive release.zip -DestinationPath "$Env:ProgramFiles\Linux Containers\."
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          [Environment]::SetEnvironmentVariable("LCOW_API_PLATFORM_IF_OMITTED", "linux", "Machine")
          Set-Content -Value "`{`"experimental`":true`}" -Path C:\ProgramData\docker\config\daemon.json
          Restart-Service docker
      - name: Check docker
        run: |
          docker version
      - name: Check LCOW
        run: |
          docker run --rm hello-world:linux