name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: [windows-latest]
    steps:
      - name: LCOW
        run: |
          Invoke-WebRequest -Uri "https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip" -UseBasicParsing -OutFile release.zip
          Expand-Archive release.zip -DestinationPath "$Env:ProgramFiles\Linux Containers\."
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          Restart-Service docker
      - name: Check docker
        run: |
          docker version