name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: [windows-latest]
    steps:
        run: |
          Set-Content -Value "`{`"experimental`":true`}" -Path C:\ProgramData\docker\config\daemon.json
          [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
          Restart-Service docker
      - name: Check docker
        run: |
          docker version